version: "3.7"
services:
  storage-of-knowledge-fe:
    image: artyomsliusar/storage-of-knowledge-fe:01
    container_name: storage-of-knowledge-fe
    ports:
      - "80:80"
    environment:
      BASE_URL:
      RECAPTCHA_PUBLIC_KEY:
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - storage-of-knowledge-be
    networks:
      - app-network

  storage-of-knowledge-be:
    image: artyomsliusar/storage-of-knowledge-be:01
    container_name: storage-of-knowledge-be
    environment:
      DJANGO_ANYMAIL:
      DJANGO_ACCESS_TOKEN_LIFETIME_MINUTES:
      DJANGO_ADMINS:
      DJANGO_ADMIN_HEADER_COLOR:
      DJANGO_ADMIN_HEADER_TITLE:
      DJANGO_ALLOWED_HOSTS:
      DJANGO_CORS_ORIGIN_WHITELIST:
      DJANGO_DATABASE_ENGINE:
      DJANGO_DATABASE_NAME:
      DJANGO_DATABASE_USER:
      DJANGO_DATABASE_PASSWORD:
      DJANGO_DATABASE_HOST:
      DJANGO_DATABASE_PORT:
      DJANGO_DEBUG:
      DJANGO_DEFAULT_FROM_EMAIL:
      DJANGO_EMAIL_BACKEND:
      DJANGO_ENVIRONMENT:
      DJANGO_ELASTICSEARCH_HOST:
      DJANGO_ELASTICSEARCH_PORT:
      DJANGO_LOGGING_CONFIG_FILE:
      DJANGO_RECAPTCHA_PRIVATE_KEY:
      DJANGO_RECAPTCHA_URL:
      DJANGO_SECRET_KEY:
      DJANGO_SERVER_EMAIL:
      DJANGO_STATIC_ROOT:
      DJANGO_USER_CONFIRMATION_LIFETIME_HOURS:
    restart: unless-stopped
    volumes:
      - ${PWD}/logging:/app/storageofknowledge/logging
    depends_on:
      - storage-of-knowledge-db
      - storage-of-knowledge-elastic
    networks:
      - app-network

  storage-of-knowledge-db:
    image: mysql:5.7
    container_name: storage-of-knowledge-db
    environment:
      MYSQL_DATABASE: ${DJANGO_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      MYSQL_ROOT_USER: ${DJANGO_DATABASE_USER}
    restart: unless-stopped
    volumes:
      - ${PWD}/db_data:/var/lib/mysql
    networks:
      - app-network

  storage-of-knowledge-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: storage-of-knowledge-elastic
    environment:
      discovery.type: "single-node"
      "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  es_data:
    driver: local